/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-11-14 06:09:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class website_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Document</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"website.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".main_logo {\r\n");
      out.write("	color: #7AB730;\r\n");
      out.write("	text-decoration-line: none;\r\n");
      out.write("	font-size: 25px;\r\n");
      out.write("	margin-left: 15%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main_title2 {\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#dropdownBtn {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	margin-left: 60%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#dropdownContent {\r\n");
      out.write("	display: none;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	background-color: #f9f9f9;\r\n");
      out.write("	min-width: 160px;\r\n");
      out.write("	box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);\r\n");
      out.write("	z-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#dropdownContent a {\r\n");
      out.write("	color: black;\r\n");
      out.write("	padding: 12px 16px;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#dropdownContent a:hover {\r\n");
      out.write("	background-color: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mid_row1 {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	text-decoration-line: none;\r\n");
      out.write("	color: #7AB730;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mid_row2 {\r\n");
      out.write("	border: 1px solid #ccc;\r\n");
      out.write("	height: 70px;\r\n");
      out.write("	padding: 15px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search {\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	padding: 8px;\r\n");
      out.write("	margin-top: 5%;\r\n");
      out.write("	margin-bottom: 5%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".info {\r\n");
      out.write("	margin-left: 10%;\r\n");
      out.write("	margin-right: 10%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".category_img {\r\n");
      out.write("	width: 500px;\r\n");
      out.write("	height: 300px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("	<form action=\"LoginServlet\" method=\"post\">\r\n");
      out.write("        <input type=\"hidden\" name=\"formAction\" value=\"userInfoForm\">\r\n");
      out.write("	\r\n");
      out.write("		<a href=\"mainpage.jsp\" class=\"main_logo\">\r\n");
      out.write("			<h1 style=\"display: inline-block;\">\r\n");
      out.write("				떠나<span class=\"main_title2\">조</span>\r\n");
      out.write("			</h1>\r\n");
      out.write("		</a> \r\n");
      out.write("		");

		String loggedIn = (String) session.getAttribute("user_id");
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<button type=\"button\" id=\"dropdownBtn\">\r\n");
      out.write("			<span>더보기</span>\r\n");
      out.write("			<div id=\"dropdownContent\" style=\"display: none;\">\r\n");
      out.write("				<a href=\"mainpage.jsp\">메인페이지</a>\r\n");
      out.write("\r\n");
      out.write("				");

				if (loggedIn != null && !loggedIn.isEmpty()) {
				
      out.write("\r\n");
      out.write("				<a href=\"myPage/user-info.jsp\">마이페이지</a>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("				<div id=\"citiesDropdown\">\r\n");
      out.write("					<a href=\"#\">도시 선택</a>\r\n");
      out.write("					<div id=\"citiesContent\" style=\"display: none;\">\r\n");
      out.write("						<a href=\"#\">교토</a> <a href=\"#\">나가사키</a> <a href=\"#\">나고야</a> <a\r\n");
      out.write("							href=\"#\">도쿄</a> <a href=\"#\">사포로</a> <a href=\"#\">시즈오카</a> <a\r\n");
      out.write("							href=\"#\">오사카</a> <a href=\"#\">후쿠오카</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				");

				loggedIn = (String) session.getAttribute("user_id");

				if (loggedIn != null && !loggedIn.isEmpty()) {
				
      out.write("\r\n");
      out.write("				<a href=\"LoginServlet\">로그아웃</a>\r\n");
      out.write("				");

				} else {
				
      out.write("\r\n");
      out.write("				<a href=\"login.jsp\">로그인</a>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			\r\n");
      out.write("		</button>\r\n");
      out.write("\r\n");
      out.write("		<div id=\"imageSlider\">\r\n");
      out.write("			<a href=\"\"><img src=\"./관광지/4. 도쿄 타워/4. 도쿄 타워/3.jpg\" class=\"top10\"\r\n");
      out.write("				alt=\"\"></a> <a href=\"\"><img\r\n");
      out.write("				src=\"../오사카/관광지/3. 오사카 성/3. 오사카 성/1.jpg\" class=\"top10\" alt=\"\"></a>\r\n");
      out.write("			<a href=\"\"><img src=\"./관광지/9. 도쿄역/9. 도쿄역/1.jpg\" class=\"top10\"\r\n");
      out.write("				alt=\"\"></a> <a href=\"\"><img\r\n");
      out.write("				src=\"../오사카/관광지/9. 도톤보리/9. 도톤보리/1.jpg\" class=\"top10\" alt=\"\"></a> <a\r\n");
      out.write("				href=\"\"><img src=\"../오사카/관광지/1. 유니버설/1. 유니버설/3.jpg\"\r\n");
      out.write("				class=\"top10\" alt=\"\"></a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- Navbar End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Header Start -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Header End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Booking Start -->\r\n");
      out.write("		<nav id=\"topMenu\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li class=\"Menu\"><a class=\"menuLink\" href=\"\">삿포로</a>\r\n");
      out.write("					<ul class=\"submenu\">\r\n");
      out.write("						<li><a href=\"#\" class=\"sub\">관광지</a></li>\r\n");
      out.write("						<li><a href=\"#\" class=\"sub\">맛집</a></li>\r\n");
      out.write("						<li><a href=\"#\" class=\"sub\">숙박</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"Menu\"><a class=\"menuLink\" href=\"\">도쿄</a>\r\n");
      out.write("					<ul class=\"submenu\">\r\n");
      out.write("						<li><a href=\"./tokyo_tour.html\" class=\"sub\">관광지</a></li>\r\n");
      out.write("						<li><a href=\"./tokyo_food.html\" class=\"sub\">맛집</a></li>\r\n");
      out.write("						<li><a href=\"./tokyo_accomodation.html\" class=\"sub\">숙박</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"Menu\"><a class=\"menuLink\" href=\"\">시즈오카</a>\r\n");
      out.write("					<ul class=\"submenu\">\r\n");
      out.write("						<li><a href=\"\" class=\"sub\">관광지</a></li>\r\n");
      out.write("						<li><a href=\"\" class=\"sub\">맛집</a></li>\r\n");
      out.write("						<li><a href=\"\" class=\"sub\">숙박</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"Menu\"><a class=\"menuLink\">나고야</a>\r\n");
      out.write("					<ul class=\"submenu2\">\r\n");
      out.write("						<li><a href=\"\" class=\"sub\">관광지</a></li>\r\n");
      out.write("						<li><a href=\"\" class=\"sub\">맛집</a></li>\r\n");
      out.write("						<li><a href=\"\" class=\"sub\">숙박</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"Menu\"><a class=\"menuLink\">교토</a>\r\n");
      out.write("					<ul class=\"submenu2\">\r\n");
      out.write("						<li><a href=\"\" class=\"sub\">관광지</a></li>\r\n");
      out.write("						<li><a href=\"\" class=\"sub\">맛집</a></li>\r\n");
      out.write("						<li><a href=\"\" class=\"sub\">숙박</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"Menu\"><a class=\"menuLink\">오사카</a>\r\n");
      out.write("					<ul class=\"submenu2\">\r\n");
      out.write("						<li><a href=\"../오사카/osaka_tour.html\" class=\"sub\">관광지</a></li>\r\n");
      out.write("						<li><a href=\"../오사카/osaka_food.html\" class=\"sub\">맛집</a></li>\r\n");
      out.write("						<li><a href=\"../오사카/osaka_accomodation.html\" class=\"sub\">숙박</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"Menu\"><a class=\"menuLink\">후쿠오카</a>\r\n");
      out.write("					<ul class=\"submenu3\">\r\n");
      out.write("						<li><a href=\"\" class=\"sub\">관광지</a></li>\r\n");
      out.write("						<li><a href=\"\" class=\"sub\">맛집</a></li>\r\n");
      out.write("						<li><a href=\"\" class=\"sub\">숙박</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("\r\n");
      out.write("				<li class=\"Menu\"><a class=\"menuLink\">나가사키</a>\r\n");
      out.write("					<ul class=\"submenu3\">\r\n");
      out.write("						<li><a href=\"\" class=\"sub\">관광지</a></li>\r\n");
      out.write("						<li><a href=\"\" class=\"sub\">맛집</a></li>\r\n");
      out.write("						<li><a href=\"\" class=\"sub\">숙박</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("		</nav>\r\n");
      out.write("\r\n");
      out.write("		<!-- Search Form -->\r\n");
      out.write("		<div class=\"search\" style=\"text-align: center;\">\r\n");
      out.write("			<input type=\"text\" class=\"\" placeholder=\"검색\"\r\n");
      out.write("				style=\"display: inline-block;\">\r\n");
      out.write("			<button type=\"button\" id=\"searchButton\">\r\n");
      out.write("				<span>검색</span>\r\n");
      out.write("			</button>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- Booking End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Blog Start -->\r\n");
      out.write("		<div class=\"container px-4 text-center\">\r\n");
      out.write("			<div class=\"row gx-5\">\r\n");
      out.write("				<div class=\"col\">\r\n");
      out.write("					<div class=\"p-3\">\r\n");
      out.write("						<div class=\"\">\r\n");
      out.write("							<a href=\"\"><img class=\"category_img\"\r\n");
      out.write("								src=\"../도쿄/숙박/1. 시즈테츠 호텔/외관.webp\" alt=\"\"></a>\r\n");
      out.write("							<div class=\"\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"\">\r\n");
      out.write("							<div class=\"\">\r\n");
      out.write("								<h6>도쿄 |</h6>\r\n");
      out.write("							</div>\r\n");
      out.write("							<a class=\"h5 m-0 text-decoration-none\" href=\"\">시즈테츠 호텔</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col\">\r\n");
      out.write("					<div class=\"p-3\">\r\n");
      out.write("						<div class=\"\">\r\n");
      out.write("							<a href=\"\"><img class=\"category_img\"\r\n");
      out.write("								src=\"../도쿄/숙박/2. 미츠이 가든/외관.webp\" alt=\"\"></a>\r\n");
      out.write("							<div class=\"\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"\">\r\n");
      out.write("							<div class=\"\">\r\n");
      out.write("								<h6>도쿄 |</h6>\r\n");
      out.write("							</div>\r\n");
      out.write("							<a class=\"h5 m-0 text-decoration-none\" href=\"\">미츠이 가든</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row gx-5\">\r\n");
      out.write("				<div class=\"col\">\r\n");
      out.write("					<div class=\"p-3\">\r\n");
      out.write("						<div class=\"\">\r\n");
      out.write("							<a href=\"\"><img class=\"category_img\"\r\n");
      out.write("								src=\"../도쿄/숙박/3. 도큐 스테이/정면.webp\" alt=\"\"></a>\r\n");
      out.write("							<div class=\"\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"\">\r\n");
      out.write("							<div class=\"\">\r\n");
      out.write("								<h6>도쿄 |</h6>\r\n");
      out.write("							</div>\r\n");
      out.write("							<a class=\"h5 m-0 text-decoration-none\" href=\"\">도큐 스테이</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col\">\r\n");
      out.write("					<div class=\"p-3\">\r\n");
      out.write("						<div class=\"\">\r\n");
      out.write("							<a href=\"\"><img class=\"category_img\"\r\n");
      out.write("								src=\"../도쿄/숙박/4. 마이스테이/외관.webp\" alt=\"\"></a>\r\n");
      out.write("							<div class=\"\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"\">\r\n");
      out.write("							<div class=\"\">\r\n");
      out.write("								<h6>도쿄 |</h6>\r\n");
      out.write("							</div>\r\n");
      out.write("							<a class=\"h5 m-0 text-decoration-none\" href=\"\">마이스테이</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row gx-5\">\r\n");
      out.write("				<div class=\"col\">\r\n");
      out.write("					<div class=\"p-3\">\r\n");
      out.write("						<div class=\"\">\r\n");
      out.write("							<a href=\"\"><img class=\"category_img\"\r\n");
      out.write("								src=\"../도쿄/숙박/5. 료칸 가모가와/정면.avif\" alt=\"\"></a>\r\n");
      out.write("							<div class=\"\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"\">\r\n");
      out.write("							<div class=\"\">\r\n");
      out.write("								<h6>도쿄 |</h6>\r\n");
      out.write("							</div>\r\n");
      out.write("							<a class=\"h5 m-0 text-decoration-none\" href=\"\">료칸 가모가와</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col\">\r\n");
      out.write("					<div class=\"p-3\">\r\n");
      out.write("						<div class=\"\">\r\n");
      out.write("							<a href=\"\"><img class=\"category_img\"\r\n");
      out.write("								src=\"../도쿄/숙박/6. 프로스타일 료칸/외관.webp\" alt=\"\"></a>\r\n");
      out.write("							<div class=\"\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"\">\r\n");
      out.write("							<div class=\"\">\r\n");
      out.write("								<h6>도쿄 |</h6>\r\n");
      out.write("							</div>\r\n");
      out.write("							<a class=\"h5 m-0 text-decoration-none\" href=\"\">프로스타일 료칸</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row gx-5\">\r\n");
      out.write("				<div class=\"col\">\r\n");
      out.write("					<div class=\"p-3\">\r\n");
      out.write("						<div class=\"\">\r\n");
      out.write("							<a href=\"\"><img class=\"category_img\"\r\n");
      out.write("								src=\"../도쿄/숙박/7. 차시츠 료칸 아사쿠사/외관.webp\" alt=\"\"></a>\r\n");
      out.write("							<div class=\"\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"\">\r\n");
      out.write("							<div class=\"\">\r\n");
      out.write("								<h6>도쿄 |</h6>\r\n");
      out.write("							</div>\r\n");
      out.write("							<a class=\"h5 m-0 text-decoration-none\" href=\"\">차치츠 료칸</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col\">\r\n");
      out.write("					<div class=\"p-3\">\r\n");
      out.write("						<div class=\"\">\r\n");
      out.write("							<a href=\"\"><img class=\"category_img\"\r\n");
      out.write("								src=\"../도쿄/숙박/8. omo5/외관.webp\" alt=\"\"></a>\r\n");
      out.write("							<div class=\"\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"\">\r\n");
      out.write("							<div class=\"\">\r\n");
      out.write("								<h6>도쿄 |</h6>\r\n");
      out.write("							</div>\r\n");
      out.write("							<a class=\"h5 m-0 text-decoration-none\" href=\"\">omo5</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row gx-5\">\r\n");
      out.write("				<div class=\"col\">\r\n");
      out.write("					<div class=\"p-3\">\r\n");
      out.write("						<div class=\"\">\r\n");
      out.write("							<a href=\"\"><img class=\"category_img\"\r\n");
      out.write("								src=\"../도쿄/숙박/9. 베스트/외관.webp\" alt=\"\"></a>\r\n");
      out.write("							<div class=\"\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"\">\r\n");
      out.write("							<div class=\"\">\r\n");
      out.write("								<h6>도쿄 |</h6>\r\n");
      out.write("							</div>\r\n");
      out.write("							<a class=\"h5 m-0 text-decoration-none\" href=\"\">베스트</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col\">\r\n");
      out.write("					<div class=\"p-3\">\r\n");
      out.write("						<div class=\"\">\r\n");
      out.write("							<a href=\"\"><img class=\"category_img\"\r\n");
      out.write("								src=\"../도쿄/숙박/10. 더 게이트/외관.jpg\" alt=\"\"></a>\r\n");
      out.write("							<div class=\"\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"\">\r\n");
      out.write("							<div class=\"\">\r\n");
      out.write("								<h6>도쿄 |</h6>\r\n");
      out.write("							</div>\r\n");
      out.write("							<a class=\"h5 m-0 text-decoration-none\" href=\"\">더 게이트</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<script>\r\n");
      out.write("			var dropdownBtn = document.getElementById(\"dropdownBtn\");\r\n");
      out.write("			var dropdownContent = document.getElementById(\"dropdownContent\");\r\n");
      out.write("\r\n");
      out.write("			dropdownBtn.addEventListener(\"click\", function() {\r\n");
      out.write("				if (dropdownContent.style.display === \"none\"\r\n");
      out.write("						|| dropdownContent.style.display === \"\") {\r\n");
      out.write("					dropdownContent.style.display = \"block\";\r\n");
      out.write("				} else {\r\n");
      out.write("					dropdownContent.style.display = \"none\";\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("			document.addEventListener(\"click\", function(event) {\r\n");
      out.write("				if (event.target !== dropdownBtn\r\n");
      out.write("						&& event.target !== dropdownContent) {\r\n");
      out.write("					dropdownContent.style.display = \"none\";\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("			let slideIndex = 0;\r\n");
      out.write("			const images = document.querySelectorAll('#imageSlider img');\r\n");
      out.write("\r\n");
      out.write("			function showSlides() {\r\n");
      out.write("				for (let i = 0; i < images.length; i++) {\r\n");
      out.write("					images[i].style.display = 'none';\r\n");
      out.write("				}\r\n");
      out.write("				slideIndex++;\r\n");
      out.write("				if (slideIndex > images.length) {\r\n");
      out.write("					slideIndex = 1;\r\n");
      out.write("				}\r\n");
      out.write("				images[slideIndex - 1].style.display = 'block';\r\n");
      out.write("				setTimeout(showSlides, 3000); // Change image every 2 seconds (2000 milliseconds)\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			showSlides(); // Start the image slider\r\n");
      out.write("		</script>\r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
